### ISSUE TITLE
hashesperspec is irrelevant

### ISSUE THREAD

**Issue by jjj092353** [Crypto-Expert/HoboNickels#21]
hashesperspec is irrelevant since netmhashps is provided - the existence of hashespersec causes a problem in mpos installations not reporting network hash properly.

```
"netmhashps" : 39.94735791,
"netstakeweight" : 30240.98261745,
"generate" : false,
"genproclimit" : -1,
"hashespersec" : 0,
```

**Comment by hclivess** [comment]
I can't find hashespersec in 1.5, is it still there? Maybe we should close this issue.

**Comment by ahmedbodi** [comment]
may not be, i'll have a look today

**Comment by ahmedbodi** [comment]
https://github.com/Crypto-Expert/HoboNickels/blob/master/src/rpcmining.cpp#L57

looks like its still there, i think this can be closed though. @hclivess agree?

**Comment by hclivess** [comment]
I agree, it's 2 years old anyway
